name: Continuous Integration of Main Workflow
run-name: Workflow number ${{github.run_number}}

on:
  push:
    branches:
      - dev

jobs:
  frontend_flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repostiory
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PWD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initialize NodeJS & Build application
        run: |
          npm install
          npm run build
